export const navigation = [
  { label: 'Home', to: '/', icon: 'home', group: 'Explore' },
  { label: 'Questions', to: '/questions', icon: 'message', group: 'Explore' },
  { label: 'Blogs', to: '/blogs', icon: 'book', group: 'Explore' },
  { label: 'Coding practice', to: '/coding', icon: 'code', group: 'Explore' },
  { label: 'Community', to: '/community', icon: 'users', group: 'Explore' },
  { label: 'My dashboard', to: '/dashboard', icon: 'grid', group: 'Your space' },
  { label: 'My submissions', to: '/submissions', icon: 'check', group: 'Your space' },
  { label: 'Notifications', to: '/notifications', icon: 'bell', group: 'Your space' },
  { label: 'My profile', to: '/profile', icon: 'user', group: 'Your space' },
  { label: 'Admin panel', to: '/admin', icon: 'shield', role: 'admin', group: 'Your space' },
  { label: 'Ask a question', to: '/ask-question', icon: 'plus' },
  { label: 'Write a blog', to: '/create-blog', icon: 'book' },
  { label: 'Tags', to: '/tags', icon: 'hash' },
]
